### ISSUE TITLE
PHP Fatal error: Uncaught exception after upgrading to 3.0.0

### ISSUE THREAD

**Issue by brrrrrrrt** [touchdesign/prestashop-sofortbanking#7] opened 2016-12-06 18:04 UTC
PS Version 1.6.1.10
after upgrading to latest Version, adding a new gateway project and entering the API Key, i get a blank white page in the frontoffice when trying to pay via Sofort. 

PHP logs:
```
PHP Fatal error:  Uncaught exception 'Exception' with message 'Sofortbanking module configuration error: Error: 401:Unauthorized' in xx/modules/sofortbanking/controllers/front/payment.php:97#012Stack trace:#012#0 xx/classes/controller/Controller.php(189): SofortbankingPaymentModuleFrontController->initContent()#012#1 xx/classes/Dispatcher.php(367): ControllerCore->run()#012#2 xx/index.php(28): DispatcherCore->dispatch()#012#3 {main}#012  thrown in xx/modules/sofortbanking/controllers/front/payment.php on line 97
```

**Comment by christingruber** [comment] 2016-12-07 09:33
It's not a bug but rather a "module configuration error", so we close this issue. The [SOFORT team](https://www.sofort.com/eng-INT/merchant/contact/) will be available if you need help.

**Closed by christingruber** 2016-12-07 09:33 UTC
Labels: invalid

**Comment by brrrrrrrt** [comment] 2016-12-07 11:18
are you sure, that a module configuration error should lead to Fatal PHP error?

**Comment by christingruber** [comment] 2016-12-07 11:24
Yes I am, it's a custom exception "Error: 401 Unauthorized".

**Comment by vavrecan** [comment] 2016-12-07 11:27
Honestly i got errors comming too - the configuration should be more smart
and report errors before. Sticked with v2.8 and notify passwords.

Dňa st, 7. dec 2016 12:24 Christin Gruber <notifications@github.com>
napísal(a):

**Comment by vavrecan** [comment] 2016-12-07 11:31
Would it be possible to add check/test function - if a configuration is valid? Thanks

**Comment by brrrrrrrt** [comment] 2016-12-07 12:01
imho: leaving customers with a blank white page or a Fatal PHP Error in case of a configuration error is unacceptable.

btw. i added a new classic project and i am 100% sure to have entered the correct ids and api key,

this is the "Serverdialog":
```
<?xml version="1.0" encoding="UTF-8"?>
<multipay version="2.0">
  <su/>
  <user_variables>
    <user_variable>2xx6</user_variable>
    <user_variable>1026xxxxxxxxxxxxxxxx670fd</user_variable>
  </user_variables>
  <amount>69.95</amount>
  <currency_code>EUR</currency_code>
  <language_code>de</language_code>
  <reasons>
    <reason>000002xx6 - H    Testhuber</reason>
    <reason/>
  </reasons>
  <success_url>http://xx.com/modules/sofortbanking/confirmation.php?transaction=-TRANSACTION-</success_url>
  <success_link_redirect>1</success_link_redirect>
  <abort_url>http://xx.com/index.php?controller=order&amp;step=3</abort_url>
  <notification_urls>
    <notification_url notify_on="untraceable,pending,received,loss,refunded">http://xx.com/modules/sofortbanking/notification.php</notification_url>
  </notification_urls>
  <interface_version>PrestaShop_1.6.1.10/Module_3.0.0</interface_version>
  <project_id>xxxxxx</project_id>
</multipay>
```
what i am also wondering is that it uses http:// instead of https:// - the shop is configured to use https:// only, especially communication regarding payment should use https://

**Comment by vavrecan** [comment] 2016-12-07 12:12
same issue here, only https and module passes http ...  :( dissapointed
with the update to v3.0.0

**Comment by brrrrrrrt** [comment] 2016-12-07 16:29
wohoo, this was quite a ride! after switching back to the old version i noticed it stopped working too, sofort.com was complaining about invalid hashes.

i double checked the passwords in the database, everything was correct, i also tried generating new passwords, but this didnt help either.

then i deactivated the module, and deleted it, then i did a new install (V3.0.0), configured it an voila! now it works, without problems!

when switching between versions i noticed weird caching issues, like showing old configuration page on the new version and vice versa, so i manually deleted the cache between each step, just to make sure (caching was disabled anyway) so the problem might also been a caching issue.

**Comment by PrestaShark** [comment] 2017-11-27 10:02
Same here
Sofortbanking module configuration error: Error: 401:Unauthorized

`Fatal error: Uncaught exception 'Exception' with message 'Sofortbanking module configuration error: Error: 401:Unauthorized' in /xxx/modules/sofortbanking/controllers/front/payment.php:97 Stack trace: #0 /xxx/classes/controller/Controller.php(189): SofortbankingPaymentModuleFrontController->initContent() #1 /xxx/classes/Dispatcher.php(367): ControllerCore->run() #2 /xxx/index.php(28): DispatcherCore->dispatch() #3 {main} thrown in /xxx/modules/sofortbanking/controllers/front/payment.php on line 97 `

Where is the problem
